# Generated by Django 3.2.3 on 2021-05-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='modelrepresentation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('visiblity', models.CharField(max_length=20)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.component')),
            ],
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='webapp.component')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='webapp.component')),
            ],
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('direction', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.operation')),
            ],
        ),
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('datatype', models.CharField(max_length=45)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.component')),
            ],
        ),
    ]
