# Generated by Django 3.2.3 on 2021-05-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='modelid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.modelrepresentation'),
        ),
    ]
