# Generated by Django 3.2.3 on 2021-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelrepresentation',
            name='modelId',
        ),
        migrations.AlterField(
            model_name='modelrepresentation',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
