# Generated by Django 3.2.3 on 2021-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210530_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrepresentation',
            name='modelid',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='modelrepresentation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
