# Generated by Django 3.2.3 on 2021-06-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210531_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='visibilty',
            new_name='visibility',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='visiblity',
            new_name='visibility',
        ),
    ]
