# Generated by Django 3.2.3 on 2021-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_component_modelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
