# Generated by Django 3.2.3 on 2021-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210602_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='visibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelrepresentation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='direction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
