# Generated by Django 3.2.3 on 2021-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210530_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrepresentation',
            name='modelid',
            field=models.CharField(max_length=45),
        ),
    ]
