# Generated by Django 3.2.3 on 2021-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_modelfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='description',
        ),
        migrations.AddField(
            model_name='modelrepresentation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
