# Generated by Django 3.2.3 on 2021-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_attribute_attrvisibilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attrVisibilty',
            field=models.CharField(max_length=45),
        ),
    ]
