# Generated by Django 3.2.3 on 2021-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_attribute_attrvisibilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
