# Generated by Django 3.2.3 on 2021-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210603_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xposition', models.IntegerField()),
                ('yposition', models.IntegerField()),
                ('content', models.TextField()),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.modelrepresentation')),
            ],
        ),
    ]
