# Generated by Django 3.2.3 on 2021-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_annotation_ownerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='xposition',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='yposition',
        ),
    ]
