# Generated by Django 3.2.3 on 2021-05-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='visiblity',
            field=models.CharField(max_length=45),
        ),
    ]
