# Generated by Django 3.2.3 on 2021-05-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_operation_visiblity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attrVisibilty',
            new_name='visibilty',
        ),
    ]
