# Generated by Django 3.2.3 on 2021-06-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210614_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='ownerid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.component'),
        ),
    ]
